/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tanelvir
 */
import java.awt.*;
import javax.swing.*;
import java.util.*;

public class Aloitusvalikko extends javax.swing.JFrame {

    /**
     * Creates new form Pelinalku
     */
    public Aloitusvalikko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yksinPeli = new javax.swing.JButton();
        kaksinPeli = new javax.swing.JButton();
        lopetusNappi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(221, 180, 106));
        jLabel1.setFont(new java.awt.Font("Junkyard", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 161, 104));
        jLabel1.setText("Tervetuloa muistipeliin!");

        yksinPeli.setText("Aloita yksinpeli");
        yksinPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yksinPeliActionPerformed(evt);
            }
        });

        kaksinPeli.setText("Aloita kaksinpeli");
        kaksinPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaksinPeliActionPerformed(evt);
            }
        });

        lopetusNappi.setText("Lopeta");
        lopetusNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetusNappiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kaksinPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yksinPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lopetusNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(yksinPeli)
                .addGap(37, 37, 37)
                .addComponent(kaksinPeli)
                .addGap(29, 29, 29)
                .addComponent(lopetusNappi)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaksinPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaksinPeliActionPerformed
        // TODO add your handling code here:
        Pelaajavalinta aloitus = new Pelaajavalinta();
        this.setVisible(false);
        aloitus.setVisible(true);
        
    }//GEN-LAST:event_kaksinPeliActionPerformed

    private void yksinPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yksinPeliActionPerformed
        // TODO add your handling code here:
        Pelaajavalinta aloitus = new Pelaajavalinta();
        this.setVisible(false);
        aloitus.setVisible(true);
        
    }//GEN-LAST:event_yksinPeliActionPerformed

    private void lopetusNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetusNappiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lopetusNappiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aloitusvalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aloitusvalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aloitusvalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aloitusvalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Aloitusvalikko().setVisible(true);
            } 
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kaksinPeli;
    private javax.swing.JButton lopetusNappi;
    private javax.swing.JButton yksinPeli;
    // End of variables declaration//GEN-END:variables
}
